### ISSUE TITLE
Initial Design Questions - Reconciling hypercore architecture with git architecture

### ISSUE THREAD

**Issue by flyingzumwalt** [CfABrigadePhiladelphia/jawn#1]
There are a lot of questions to answer about reconciling hypercore patterns with our use cases.  This discussion will be hosted in a public Google Hangouts discussion.

**Call Time**: Wed, Feb 10, 11:00 AM - 12:00 PM EST 
**Watch the Recorded Discussion** on YouTube: https://youtu.be/vvC0RTnm-iU

**Topics & Notes** in the public document [Dat Tables Initial Design/Architecture Topics](https://docs.google.com/document/d/1NBgLnqyI6Fv1q1c6u-hQH0LWB2_qn0nC8ZoZ8Et-iUI/edit?usp=sharing)

**Comment by flyingzumwalt** [comment]
@mafintosh @maxogden @karissa I have a handful of questions about the architecture of hypercore and how we will/should use it for 'dat-tables'.  When/how is the best way to seek answers to these questions? I've been collecting the questions in the public document [Dat Tables Initial Design/Architecture Topics](https://docs.google.com/document/d/1NBgLnqyI6Fv1q1c6u-hQH0LWB2_qn0nC8ZoZ8Et-iUI/edit?usp=sharing).

**Comment by mafintosh** [comment]
@flyingzumwalt i'd be happy to jump on a call with you next week and clear these things out for you if you want?

**Comment by flyingzumwalt** [comment]
I'm wide open 11am-5pm US Eastern all week except Thursday. What time works for you?

**Comment by mafintosh** [comment]
what about 11am EST wed?

**Comment by flyingzumwalt** [comment]
Perfect. I've set up an on-air Hangout.  Adding the info to the top of this issue.

**Comment by okdistribute** [comment]
I'll be around too!

**Comment by flyingzumwalt** [comment]
@karissa Great! I've been reading through the the hyperdrive spec, the hypercore code and the (old) dat-core code in order to make the most of our conversation.  Do either of you have suggestions of other things I should read through?

**Comment by mafintosh** [comment]
@flyingzumwalt thats should be enough to get a decent understanding on how things work.

**Comment by flyingzumwalt** [comment]
Great call. Thanks @mafintosh.  @karissa sorry for the hangouts malfunction.

Watch the Recorded Discussion on YouTube: https://youtu.be/vvC0RTnm-iU
Topics & Notes in the public document [Dat Tables Initial Design/Architecture Topics](https://docs.google.com/document/d/1NBgLnqyI6Fv1q1c6u-hQH0LWB2_qn0nC8ZoZ8Et-iUI/edit?usp=sharing)
