### ISSUE TITLE
Document what we do and don't understand about hypercore

### ISSUE THREAD

**Issue by flyingzumwalt** [CfABrigadePhiladelphia/jawn#18]
... so that we can ask @mafintosh for clarification

**Comment by clamorisse** [comment]
I can take this issue

**Comment by flyingzumwalt** [comment]
Some questions from tonight's discussion to include in the document:

**Q:** If `feed1` contains blocks `A, B, C, D` and then I create feed2 that adds blocks `E, F G`, does `feed2` have a reference to feed1 or does it just reference all of the blocks it cares about?  In other words, does feed2 look like `[feed1, E, F, G]` or does it look like `[A, B, C, D, E, F G]` with no reference to `feed1`? (See [Adding More Rows](https://github.com/CfABrigadePhiladelphia/jawn/wiki/Turning-Tabular-Data-into-Block-Chains#adding-more-rows) section within the related wiki page.

**Q:** How do we represent updating an existing row or deleting an existing row? What does that look like in the DAG? Is the notion of "add row", "update row x" or "delete row x" something that we should put into the JSON inside of blocks, or is there a way to manipulate the feed so that it's clear that a specific row has been updated or deleted?

For example: _Remember, with Jawn, each row of tabular data is a block._ 
1. I add 4 rows to a feed and then finalize it, giving me  `feed1` which contains 4 blocks `A, B, C, D`
2. I then add add 3 rows  `E, F G`, giving me `feed2`
3. I delete row `B`. **What does that look like in `feed3`?**

**Comment by flyingzumwalt** [comment]
We had a great discussion with mafintosh. Here's the [recording on YouTube](https://youtu.be/qDIjryLzYw8) and the  [event page](https://plus.google.com/events/ci1n25slnhpov05uvihh81gj5gk)

The questions that @clamorisse put together: 
https://docs.google.com/document/d/1Pv5rZoxd2HboIJkX0VtMM94QySTuuvljmvt98KMoFME/edit?usp=sharing

Also check out the very useful [diagrams that help clarify discussions about blocks & feeds](https://docs.google.com/presentation/d/1By4l9DZiJjv76425F4gzPh-KHU60EoTGpzYmbxgLQqw/edit﻿)
