### ISSUE TITLE
Pick a Name for the Project

### ISSUE THREAD

**Issue by flyingzumwalt** [CfABrigadePhiladelphia/jawn#2]
What’s in a name?  
## Option: dat-tables

There is already a prominent jQuery project called DataTables. Also dat is nearly impossible to find by entering ‘dat’ or ‘dat data’ in a search engine.
## Option: hypertable

There is already an open source project called hypertable. Hypercore and hyperdrive are also pretty tapped out in terms of SEO.  
## Option: jawn

Someone suggested that if we wanted to add local Philly flavor to the project we should call it [jawn](http://citypaper.net/Blogs/The-etymology-of-jawn/), which is a Philly slang word.  It's _"an all-purpose word to refer to different types of things and people"_.  

I (Matt) am not from Philly, so I don't know the cultural connotations of this term, but it does work from a semantic context and an SEO perspective.  It also leaves room for a 4-letter command line name `jawn` or even an abbreviated 3-letter command name `jwn`.
## Option: dat-jawn

At the Philly Node.js Meetup, someone pointed out that "dat jawn" actually fits with common (spoken) usage of the term "jawn".  Example: "Hand me dat jawn." or "What's up with dat jawn?"
## Other Options?

Any Suggestions?

**Comment by titlecharacter** [comment]
Possible SEO conflict - there's a "Data jawn" event that's happened once and is meant to be an annual one, basically a data-oriented tech conference. Still not a terrible option. Table jawn?

**Comment by flyingzumwalt** [comment]
Having an annual philly event called Data Jawn might not be a bad thing in terms of visibility for an open source project called jawn.

**Comment by flyingzumwalt** [comment]
[Video: WTF is a Jawn?](https://www.youtube.com/watch?v=SrSNS__-lvE) (_Warning: Some Explicit Language_)
"Jawn is a universal word for everything."

**Comment by flyingzumwalt** [comment]
At the Philly Node.js Meetup last night, someone pointed out that "dat jawn" actually fits with common (spoken) usage of the term "jawn". Example: "Hand me dat jawn." or "What's up with dat jawn?"

**Comment by flyingzumwalt** [comment]
We're going with **jawn**.
