### ISSUE TITLE
Story: Import a CSV File into a Feed

### ISSUE THREAD

**Issue by flyingzumwalt** [CfABrigadePhiladelphia/jawn#3]
Given a CSV file, add its contents to a hypercore feed, representing each row as one block in the feed.  
## Suggestions

Consider using [parse-input-stream](https://github.com/karissa/parse-input-stream) -- See how it was used in the [dat 2015 beta](https://github.com/flyingzumwalt/dat-2015-beta/blob/43eeff2cfe800c310bd2d4342cdefbd767652084/lib/import.js#L5)

**Comment by wtkm7** [comment]
I started working on this.
