### ISSUE TITLE
NPM Badges in Readme

### ISSUE THREAD

**Issue by flyingzumwalt** [CfABrigadePhiladelphia/jawn#6]
Add Badge from https://nodei.co/ to the readme file

**Comment by CameronSima** [comment]
Hey, I'd like to work on this ticket

**Comment by CameronSima** [comment]
Just want to be clear, adding the badge involves publishing the project to NPM -- do you want me to go ahead with that?

**Comment by flyingzumwalt** [comment]
Aha. Hmm. We should probably wait until we have some code before pushing to NPM.

**Comment by flyingzumwalt** [comment]
... but if we push the empty code base, at least we claim the name in NPM.

**Comment by flyingzumwalt** [comment]
closed by #19
